source: src
target: www
indexTemplate: src/index-template.html
postTemplate: src/post-template.html
order: ascending
maxImageDimension: 700
executeExample: git add . && git commit - a - m "💬 blog update `date`" && git push